select 'nasir ullah baig' as full_name, 
regexp_substr('Mustanisr billah', '[^ ]+', 1, 1) as first_name,
regexp_substr('Mustanisr billah', '[^ ]+', 1, 2) as Middle_name,
regexp_substr('Mustanisr billah', '[^ ]+', 1, 3) as last_name
from dual;

CREATE TABLE NAMES(
    FULLNAME VARCHAR2(20)
);
INSERT INTO NAMES(FULLNAME) 
VALUES ('NASIR ULLAH BAIG');
INSERT INTO NAMES(FULLNAME) 
VALUES ('FAIZAN ALAM');
INSERT INTO NAMES(FULLNAME) 
VALUES ('MUSTANSIR BILLAH');
INSERT INTO NAMES(FULLNAME) 
VALUES ('JAVEED');


SELECT * FROM NAMES;
--INSTR(string, substring, position, occurrence)
--SUBSTR(string, start_position, length)
SELECT FULLNAME,
NVL(SUBSTR(FULLNAME, 1, INSTR(FULLNAME, ' ', 1, 1) -1), FULLNAME) AS FIRST_NAME,--5
SUBSTR(FULLNAME,
        INSTR(FULLNAME, ' ', 1, 1) + 1, --7
        INSTR(FULLNAME, ' ', 1, 2) - INSTR(FULLNAME, ' ', 1, 1) - 1) AS middle_name_instr,--12 -6 -1 = 5
--NVL2(expression1, expression2, expression3)
NVL2(INSTR(FULLNAME, ' ', 1, 1),        
        SUBSTR(FULLNAME,
                   INSTR(FULLNAME, ' ', 1, DECODE(INSTR(FULLNAME, ' ', 1, 2), 0, 1, 2)) + 1,
                   LENGTH(FULLNAME)), 
                   NULL )AS last_name_instr 
FROM NAMES;


--Below we will use the case funtion to handle the above cases.
SELECT FULLNAME,
--FOR FIRST NAME
NVL(SUBSTR(FULLNAME, 1, INSTR(FULLNAME, ' ', 1, 1) -1), FULLNAME) AS FIRST_NAME,
--FOR MIDDLE NAME
CASE
    WHEN INSTR(FULLNAME, ' ', 1, 2) > 0
        THEN SUBSTR(FULLNAME,
            INSTR(FULLNAME, ' ', 1, 1) +1,
            INSTR(FULLNAME, ' ', 1, 2) - INSTR(FULLNAME, ' ', 1, 1) -1)
        ELSE
            NULL
END AS MIDDLE_NAME,
--FOR LAST NAME
CASE
    WHEN INSTR(FULLNAME, ' ', 1, 1) = 0
        THEN NULL
    ELSE
        SUBSTR(FULLNAME,
            INSTR( FULLNAME, ' ', 1, DECODE(INSTR(FULLNAME, ' ', 1, 2), 0, 1, 2)) + 1, LENGTH(FULLNAME))
END AS LAST_NAME
FROM NAMES;




SELECT 'GHULAM MUJTABA ADIL', SUBSTR('GHULAM MUJTABA ADIL',1,NVL(NULLIF(INSTR('GHULAM MUJTABA ADIL',' '),0),LENGTH('GHULAM MUJTABA ADIL')+1) -1)
FROM DUAL;
/
SELECT 'GHULAM MUJTABA ADIL',LENGTH('GHULAM MUJTABA ADIL') -----19
FROM DUAL;
/
SELECT 'GHULAM MUJTABA ADIL',INSTR('GHULAM MUJTABA ADIL',' ')--7
FROM DUAL;
/
SELECT 'GHULAM MUJTABA ADIL',NULLIF(7,0) --7
FROM DUAL;
/
SELECT 'GHULAM MUJTABA ADIL', NVL(7,19)
FROM DUAL;
/
SELECT 'GHULAM MUJTABA ADIL', SUBSTR('GHULAM MUJTABA ADIL',1,7)
FROM DUAL;

SELECT 'GHULAM MUJTABA ADIL',SUBSTR('GHULAM MUJTABA ADIL',1,NVL(NULLIF(INSTR('GHULAM MUJTABA ADIL',' '),0), LENGTH('GHULAM MUJTABA ADIL')+1)-1)
FROM DUAL;












